### PR TITLE
Merged PM Driver Updates from Aurora 3.5 thanks @neobuddy89 for TIP.

### PR DESCRIPTION
**Pull request by danielstuart14**

### CODE REVIEW

**Comment by Rashed97** [comment]
Whats the original CAF commit that this is from? I want to preserve authorship as much as possible.

**Comment by ZdrowyGosciu** [comment]
And what does it really change?

**Comment by danielstuart14** [comment]
It's a new PM driver, that offer a better battery consumption when screen is off. 
I'll try to get the original commit, since wasn't I that figure it out, I don't have the original one. But, the "v2-pm.dtsi" from shamu's 3.10 already has it: https://android.googlesource.com/kernel/msm/+/android-msm-shamu-3.10-lollipop-release/arch/arm/boot/dts/qcom/msm8974-v2-pm.dtsi

But how you can see, it has a new path to qcom dts, as all the others 3.10 kernels. 
This commit has been used in dorimanx's kernels a long time ago.

**Comment by ZdrowyGosciu** [comment]
https://github.com/dorimanx/Dorimanx-LG-G2-D802-Kernel/commit/5a2585c6251146bc561422ac3ea8109f370d1110
@Rashed97 what do You think? :)

**Comment by Rashed97** [comment]
I'm not convinced yet, but I'll try it out and see.

**Comment by danielstuart14** [comment]
@ZdrowyGosciu This dori's commit is the same as mine, but I changed it since all the other files are already updated in 5.0.2 lg sources.

 Here it's in dori's LP source: https://github.com/dorimanx/DORIMANX_LG_STOCK_LP_KERNEL/commit/32f2df572ba4cd4abf9e590c214ad537f56748bc

**Comment by Rashed97** [comment]
What we should probably do is update all of LG's DTB files since they look like they havent been updated in years.

**Comment by ZdrowyGosciu** [comment]
:+1:

**Comment by danielstuart14** [comment]
I recommend update kernel tree to 3.4.107 too.
If you want, I merged all the changes in only one with the conflics solved: https://github.com/danielstuart14/android_kernel_lge_msm8974/commit/b596199eff4dbbe3e61517a472b2ea36c7212c1d
Tested and working with any error. It's ONLY kernel patches between 3.4.0 and 3.4.107.

**Comment by danielstuart14** [comment]
Here the commit is: https://android.googlesource.com/kernel/msm.git/+/c439c2abce1a3eea90afc9083462f8d2bc276d62

Just need be merged! :D

**Comment by Rashed97** [comment]
@danielstuart14 I will not update the kernel to 3.4.107, stock CodeAurora is 3.4.0.

**Comment by Rashed97** [comment]
https://github.com/lg-devs/android_kernel_lge_msm8974/commit/420eabbfb9dd30fc21319e011f02ffd9febcd0a2

**Pull request closed without merging**
